import './globals.css'
import type {Metadata} from 'next'
import {Inter} from 'next/font/google'
import {ColorSchemeScript, MantineProvider} from '@mantine/core';

const inter = Inter({subsets: ['latin']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <html lang="en">
      <head>
        <ColorSchemeScript/>
        <title>Sample Project</title>
      </head>
      <body className={inter.className}>
      <MantineProvider>
        {children}
      </MantineProvider>
      </body>
      </html>
  )
}
