name: 🛠️ Bug Report
description: Report a bug in the application
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: "## Reporting a Bug"
  - type: markdown
    attributes:
      value: |
        Don't worry about duplicate issues. Just ask what you want ^^
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe the issue you are facing.
    validations:
      required: true

  - type: dropdown
    id: source
    attributes:
      label: App Edition
      description: Which flavor of the app this bug is present in?
      multiple: false
      options:
        - Pocket Edition (Play Store)
        - Standard Edition (Play Store)
        - Lite Edition (F-Droid/IzzyOnDroid)
        - Web Edition (On the Web)
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Are there any specific steps I can take to reproduce this issue?
      placeholder: |
        Are there any specific steps I can take to reproduce this issue?
    validations:
      required: false
  - type: textarea
    id: extra
    attributes:
      label: Screenshots & Videos
      placeholder: |
        Adding screenshots and videos helps a lot!