name: ✨ Feature Request
description: Suggest a Feature
labels: [ "enhancement" ]
body:
  - type: markdown
    attributes:
      value: "## Request a new feature"
  - type: markdown
    attributes:
      value: |      
        Just ask away! No need to duplicate issues first. Also, welcome :)
        
        Design Principle:
        ---
        "Less is more" | A great experience beats any feature list, all the time.
        
        Roadmap (good to browse first) --> https://suvam.io/dhaaga/roadmap

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to be added in the app? How can it improve the SNS experience for everyone?
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Links, Images and Videos
      description: |
        Add links/images/videos relevant to the request *(can be from other 
        apps or websites)*.