name: ✨ Feature Request
description: Suggest a Feature
labels: [ "enhancement" ]
body:
  - type: markdown
    attributes:
      value: "## Request a new feature"
  - type: markdown
    attributes:
      value: |
        Welcome, and thank you for taking the time to suggest improvements to 
        the app. 🙏
        
        * No need to search for duplicate issues. Just ask away.
        * Dhaaga stresses on minimizing setting bloat and shipping good 
        design out of the box.
          - As such, requests for *(non-critical)* UI toggles and alternate 
        layouts may get dropped. I hope you understand 🙇‍♂️
          - I make an exception for app theming, though. Go ham for that. 😉 

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to be added to Dhaaga? How can it benefit all users?
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Screenshots and Videos
      description: |
        If you are referencing existing features from any other website/app, 
        direct screenshots would save a lot of time!