name: ✨ Feature Request
description: Suggest a Feature
labels: [ "enhancement" ]
body:
  - type: markdown
    attributes:
      value: "## Request a new feature"
  - type: markdown
    attributes:
      value: |
        Welcome, and thank you for your time 🙏
        
        * Just ask away. No need to search for duplicate issues.
        * Please don't mind if I vote against a proposed change.
          * Crafting a good experience takes a lot of thought and attention.
          * And, Dhaaga is designed to be an enhancement rather than just a tool.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: What would you like to be added in the app? How can it improve the SNS experience for everyone?
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Links, Images and Videos
      description: |
        Add links/images/videos relevant to the request *(can be from other 
        apps or websites)*.