// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DashboardSearchUsers(arg1) {
  return window['go']['main']['App']['DashboardSearchUsers'](arg1);
}

export function GetAccount(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetAccount'](arg1, arg2, arg3);
}

export function GetAccoutsBySubdomain(arg1, arg2) {
  return window['go']['main']['App']['GetAccoutsBySubdomain'](arg1, arg2);
}

export function GetAsset(arg1) {
  return window['go']['main']['App']['GetAsset'](arg1);
}

export function GetCredentialsByAccountId(arg1) {
  return window['go']['main']['App']['GetCredentialsByAccountId'](arg1);
}

export function GetCustomDeviceId() {
  return window['go']['main']['App']['GetCustomDeviceId']();
}

export function GetDatabasePostInfo(arg1) {
  return window['go']['main']['App']['GetDatabasePostInfo'](arg1);
}

export function GetDownloadsFolder() {
  return window['go']['main']['App']['GetDownloadsFolder']();
}

export function GetImagesForProfile(arg1) {
  return window['go']['main']['App']['GetImagesForProfile'](arg1);
}

export function GetImagesFromThread(arg1) {
  return window['go']['main']['App']['GetImagesFromThread'](arg1);
}

export function GetSubdomainsForDomain(arg1) {
  return window['go']['main']['App']['GetSubdomainsForDomain'](arg1);
}

export function GetTextFeedUsingCursor(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetTextFeedUsingCursor'](arg1, arg2, arg3);
}

export function GetUserDataDirectory() {
  return window['go']['main']['App']['GetUserDataDirectory']();
}

export function InstagramSafeLogin(arg1, arg2) {
  return window['go']['main']['App']['InstagramSafeLogin'](arg1, arg2);
}

export function SearchUsers(arg1) {
  return window['go']['main']['App']['SearchUsers'](arg1);
}

export function SelectDownloadsFolder() {
  return window['go']['main']['App']['SelectDownloadsFolder']();
}

export function SetCustomDeviceId(arg1) {
  return window['go']['main']['App']['SetCustomDeviceId'](arg1);
}

export function SetUserFavourite(arg1) {
  return window['go']['main']['App']['SetUserFavourite'](arg1);
}

export function UnsetUserFavourite(arg1) {
  return window['go']['main']['App']['UnsetUserFavourite'](arg1);
}

export function UpsertAccount(arg1) {
  return window['go']['main']['App']['UpsertAccount'](arg1);
}

export function UpsertCredential(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpsertCredential'](arg1, arg2, arg3);
}
