// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAsset(arg1) {
  return window['go']['main']['App']['GetAsset'](arg1);
}

export function GetImagesForProfile(arg1) {
  return window['go']['main']['App']['GetImagesForProfile'](arg1);
}

export function GetImagesFromThread(arg1) {
  return window['go']['main']['App']['GetImagesFromThread'](arg1);
}

export function SearchUsers(arg1) {
  return window['go']['main']['App']['SearchUsers'](arg1);
}

export function Startup() {
  return window['go']['main']['App']['Startup']();
}
