// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {threadsapi} from '../models';

export function GetAsset(arg1:string):Promise<string>;

export function GetImagesForProfile(arg1:string):Promise<Array<string>>;

export function GetImagesFromThread(arg1:string):Promise<Array<string>>;

export function SearchUsers(arg1:string):Promise<Array<threadsapi.ThreadsApi_User>>;

export function Startup():Promise<boolean>;
