// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImagesFromThread(arg1:string):Promise<Array<string>>;

export function Greet(arg1:string):Promise<string>;
