// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAsset(arg1:string):Promise<Array<number>>;

export function GetImagesForProfile(arg1:string):Promise<Array<string>>;

export function GetImagesFromThread(arg1:string):Promise<Array<string>>;
