version = 0.1

[default.deploy.parameters]
stack_name = "DhaagaProxyServices-stack"
resolve_s3 = true
s3_prefix = "DhaagaProxyServices-stack"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
