name: 'Build Standard Edition Locally'

on:
  push:
    branches: ['**']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5 # Checkout
        with:
          lfs: true
      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 21
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - uses: actions/setup-node@v5 # Install Node.js
        with:
          node-version: latest
          cache: "npm"
      - run: npm install # Install dependencies
      - run: npm run build-deps
      # - run: npm run build # Taken care of by "eas-build-post-install" hook
      - uses: expo/expo-github-action@v8 # setup EAS
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - run: eas build --local --profile=lite --non-interactive --platform=android --output=./output/dhaaga.apk # build app
        working-directory: ./apps/mobile
      - uses: actions/upload-artifact@v4 # upload artifacts
        with:
          name: app apk
          path: |
            dist
            !dist/**/*.md