on:
  push:
    branches:
      - production
      - fix/main-ci-for-pnpm
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # pull code
        with:
          lfs: true
      - uses: actions/setup-node@v4 # setup node
        with:
          node-version: latest
      - uses: pnpm/action-setup@v4
        with:
          version: 10
          # NOTE: remove optional dependencies for lite builds
          run_install: |
            - recursive: false
              args: []
      - uses: expo/expo-github-action@v8 # setup EAS
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - run: eas build --non-interactive --platform=android # build app
        working-directory: ./apps/mobile